### ISSUE TITLE
This particular addon doesn't seem to want to work in BfA, but works great in Frostfire Ridge though

### ISSUE THREAD

**Issue by Swirrel** [mikepauer/Carbonite.Gathermate2_Data#1]
Hi.

So I've finally gotten to a stage where running around as a headless chicken trying to farm herbs is doing my head in, so I thought I'd go ahead and turn on Carbnoite. Gathermate2_Data (Carb Gather for short).
Now I remembered to have read somewhere, that after you turn it on, you had to delete the Old Data and then reimport the New Data.
I had made sure that I had the newest Alpha version through the Twitch Client, so I enter the game and log in on Jag as he's my herbalist. I do exactly as above (delete old data and import new data). As I don't want everything to be loaded in I have only selected the Herbs that are native to BfA, as well as the Ores that are native to BfA. I see no reason in importing a ton of data from prior expansions that I don't need or want... (I do think it loaded those any way though, though they're turned of on my end - 31937 items seemed a lot though that's only when clicking on Import Herbs).
As nothing happend on my Carb Map in terms of herb locations showing up,. I HS'd to my Garrison, flew out to Frostfire Ridge (I'm horde, so it's closest to my Garrison), I made sure it said Frostfire Ridge before trying anything.
Okay, so right clicking on:
Carb Map choosing: Transparency: Gather Icon Transparency and set it to max.
and
Carbonite Map choosing: Scale: Gather Icons at Scale and set it to max
I can't see why either should make a difference as it wasn't necessary in Legion, but hey... it's tried and tested, so then I figure.. I'll try to turn on: Carbonite Weekly, Items, Notes and Info, to see if either of that would make any difference and while hanging there in Frostfire Ridge in flightform, I also turn on frostweed as that's a herb that can spawn in Frostfire Ridge and waiting around 5 minutes time, they suddenly popped up. So I figure I'll turn of Carbonite Weekly, Items, Notes and Info and see what happens. I did that and the Frostweed icons are still there.
Great I think and HS back to Zuldazar and am disappointed when nothing shows. So I think, let me leave the city to hand in my Emmisary for Tortollan Seekers, so I take the taxi to Scaletrader Post. Not one bit did it help me. 
As I hadn't changed a thing since I left Frostfire Ridge, it should technically still be working.

So what am I missing?

Thank you.
Jag.

**Comment by IrcDirk** [comment]
As u can read from description of this addon "Direct copy of gathermate2_data node information customized for Carbonite import". Gathermate2_data addon was not yet updated for BfA, so there are no nodes for BfA, yet. I will update it when new version of gathermate2_data will be available.

But till then u can use https://wow.curseforge.com/projects/wowgatheringnodes which have BfA nodes and has module to Import those nodes to Carbonite.

**Comment by Swirrel** [comment]
I've been reluctant to use any addons with regards to gathering when I have Carbonite. They haven't worked well together in the past, but I'll give that link a go tomorrow.

Thank you.

Ps. Is there anything I can do to help with the nodes I pick up in game when herbing or mining?

**Comment by IrcDirk** [comment]
This addon is really just collection of data for nodes, herbs etc. is really similar to Gathermate2_Data. U just import data to Carbonite then u can delete it.

As to help, no thanks, we need to wait till Gathermate2_Data will scrap data from wowhead then ill update this module.

**Comment by Swirrel** [comment]
Since I installed that addon my world quests keep disappearing from the Map. That goes for both my lvl 120's... It may be a coinsidence, but I can't help thinking that there is a connection.
